### ISSUE TITLE
Error al pagar - No such entity with orderId

### ISSUE THREAD

**Issue by neutronixx** [conekta/conekta-magento2#29]
Hola, tenemos el siguiente error al intentar colocar el la orden usando Conekta como método de pago:

{"message":"No such entity with orderId = ","trace":"#0 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(22, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...', Array)\n#2 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(22, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#3 \/home\/magestore\/public_html\/ak\/v2\/generated\/code\/Magento\/Checkout\/Model\/PaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n#4 [internal function]: Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder(22, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#5 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/module-webapi\/Controller\/Rest.php(330): call_user_func_array(Array, Array)\n#6 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/module-webapi\/Controller\/Rest.php(239): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#7 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/home\/magestore\/public_html\/ak\/v2\/vendor\/magento\/framework\/Interception\/

Gracias!

**Comment by silvaGarduno** [comment]
Hola @neutronixx. perdón por la demora.

El error que nos mandas no es muy especifico al igual que tu descripción.
Entiendo que estas utilizando magento para poder procesar con nosotros? 
Que version de magento estas manejando y version de PHP?
