### ISSUE TITLE
Exception #0 (LogicException): Front controller reached 100 router match iterations

### ISSUE THREAD

**Issue by hcontreras** [conekta/conekta-magento2#35]
Qué tal.

Sé que este Issue ya estaba reportado pero actualmente está cerrado y sin retroalimentación.

Esta es la configuración de mi ambiente:
```
PHP v7.1.26
Magento 2.2.6
conekta-magento2 v2.0.2
```
Aunque en este último dato tengo mis dudas, ya que la gente de soporte me dice que ya existe una v2.0.3 pero el repo sigue diciendo v2.0.2 a pesar de que el tag va en v2.0.3

Este es el id del último commit: `b251f7458e97005db7358a692b96c7d163a82a73`

El caso es que hago la instalación según la documentación del repo, sigo la guía de integración paso a paso y aunque es para Magento 1.x es intuitiva y se puede replicar perfectamente para Magento 2.x y obtengo este error.

```
1 exception(s):
Exception #0 (LogicException): Front controller reached 100 router match iterations

Exception #0 (LogicException): Front controller reached 100 router match iterations
#0 /var/www/persianasycortinas.com/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#1 /var/www/persianasycortinas.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#2 /var/www/persianasycortinas.com/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#3 /var/www/persianasycortinas.com/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /var/www/persianasycortinas.com/app/code/TemplateMonster/LayoutSwitcher/Model/App/Action/ContextPlugin.php(40): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#5 /var/www/persianasycortinas.com/vendor/magento/framework/Interception/Interceptor.php(135): TemplateMonster\LayoutSwitcher\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#6 /var/www/persianasycortinas.com/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /var/www/persianasycortinas.com/app/code/TemplateMonster/SiteMaintenance/Model/PageCache/App/FrontController/BuiltinPlugin.php(34): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /var/www/persianasycortinas.com/vendor/magento/framework/Interception/Interceptor.php(135): TemplateMonster\SiteMaintenance\Model\PageCache\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /var/www/persianasycortinas.com/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /var/www/persianasycortinas.com/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#11 /var/www/persianasycortinas.com/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/persianasycortinas.com/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#13 /var/www/persianasycortinas.com/index.php(43): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#14 {main}
```
A pesar de que durante la configuración, mi Magento va y da de alta los Webhooks de forma automática, estos son creados con estatus de error. No importa si los creo manualmente, el resultado es el mismo.

Ya leí también los issues relacionados sin encontrar alguna solución para aplicar.

Quedo atento a sus comentarios.

Gracias

**Comment by jazomr** [comment]
@hcontreras puedes probar con mi Fork en https://github.com/jazomr/conekta-magento2 y si te funciona quizás nos puede ayudar @eduenriquez a hacer el merge
